name: 每小时抓取咪咕直播源
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  crawl_job:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 配置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装项目依赖
        run: pip install -r requirements.txt

      - name: 执行抓取脚本
        run: python main.py

      - name: 提交更新文件
        run: |
          git config --global user.name "auto-crawl"
          git config --global user.email "crawl@example.com"
          git add iptv_source.txt
          git commit -m "定时更新直播源 $(date +'%Y-%m-%d %H:%M')"
          git push
