name: 每小时抓取咪咕直播源
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  crawl_job:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装系统浏览器依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y libwoff-dev libgstreamer1.0-0 libgstreamer-plugins-base1.0-0

      - name: 安装python依赖
        run: pip install -r requirements.txt

      - name: 安装playwright浏览器内核
        run: playwright install chromium

      - name: 执行抓取脚本
        run: python main.py

      - name: 提交更新文件
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add iptv_source.txt
          git commit -m "定时更新直播源 $(date +'%Y-%m-%d %H:%M')"
          git push
